mod author;
mod author_with_books;
mod book;
mod book_with_author_series;
mod language;
mod review;
mod serie;
pub use author::{Author, IAuthorRepository};
pub use author_with_books::AuthorWithBooks;
pub use book::{Book, IBookRepository};
pub use book_with_author_series::BookWithAuthorSerieReviews;
pub use language::{Glossary, ILanguageRepository, Language};
pub use review::{IReviewRepository, Review};
pub use serie::{ISerieRepository, Serie};
